spring.application.name=server
spring.profiles.active=prod

# Database configuration properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

jwt.secret-key= e22daa655ec6a696c789c6e1e850631df22d09af38aa9b9431fd3af6cc4c96d2
# 15 minutes for jwt
jwt.expiration= 900000
# 30 minutes for refresh jwt
jwt.refresh-expiration = 1800000

# Document storage properties
document.upload-directory=doc-uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
